AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  browser-fighting-game-instance-management

  SAM template for instance management APIs, used in the browser
  fighting game to assign game instances to lobbies for hosting
  the game arena.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
### Game instance table ###
  InstanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
### Instance allocation API ###
  InstanceAllocationApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  GameStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/instance_allocation/game_start
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref InstanceTable
      Events:
        GameStart:
          Type: Api
          Properties:
            Path: /instance_allocation/game_start
            Method: post
            RestApiId: !Ref InstanceAllocationApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InstanceTable
        - DynamoDBWritePolicy:
            TableName: !Ref InstanceTable
### Game instance internal API ###
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  InstanceAllocationApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${InstanceAllocationApi}.execute-api.${AWS::Region}.amazonaws.com/instance_allocation/game_start"
  GameStartFunction:
    Description: "GameStart Lambda Function ARN"
    Value: !GetAtt GameStartFunction.Arn
  GameStartFunctionIAMRole:
    Description: "Implicit IAM Role created for GameStart function"
    Value: !GetAtt GameStartFunction.Arn
  InstanceTable:
    Description: "DynamoDB table created for tracking available game instances"
    Value: !Ref InstanceTable
